/**
 * tokens.ts
 *
 * GENERATED BY BRIDGE — DO NOT MODIFY MANUALLY.
 * Run `/design-workflow setup` to regenerate from Figma variables.
 *
 * Extracted from: Jint SharePoint Webpart's Library (367iRLkGBReWbR3Vp61bbJ)
 * Extracted on: 2026-03-26
 *
 * Token naming follows semantic Tailwind conventions (sm/md/lg) mapped from Figma names.
 * Color tokens (sp-*) are handled separately by generateThemePalette.ts.
 */

export const figmaTokens = {
  /**
   * Spacing tokens — used for padding, gap, margin
   * Figma names: None/XXS/XS/SNudge/S/MNudge/M/L/XL/XXL/XXXL
   * Tailwind usage: p-md, gap-lg, m-sm, etc.
   */
  spacing: {
    'none':     '0px',
    '2xs':      '2px',   // XXS
    'xs':       '4px',   // XS
    'sm-nudge': '6px',   // SNudge
    'sm':       '8px',   // S
    'md-nudge': '10px',  // MNudge
    'md':       '12px',  // M
    'lg':       '16px',  // L
    'xl':       '20px',  // XL
    '2xl':      '24px',  // XXL
    '3xl':      '32px',  // XXXL
  },

  /**
   * Typography tokens — font size + line height pairs
   * Figma style names: text-{size}/leading-{type}/{weight}
   * Tailwind usage: text-body, text-heading, text-caption, etc.
   */
  fontSize: {
    'caption':    ['10px', { lineHeight: '1' }],     // text-xxs/leading-none
    'body':       ['14px', { lineHeight: '20px' }],  // text-sm/leading-normal
    'heading-sm': ['20px', { lineHeight: '1' }],     // text-xl/leading-none
    'heading':    ['24px', { lineHeight: '32px' }],  // text-2xl/leading-normal
    'heading-lg': ['30px', { lineHeight: '36px' }],  // text-3xl/leading-normal
  },

  /**
   * Border radius tokens
   * Figma names: None/Small/Medium/Large/X-Large/Circular
   * Tailwind usage: rounded-sm, rounded-md, rounded-lg, etc.
   */
  borderRadius: {
    'none':     '0px',
    'sm':       '2px',      // Small
    'md':       '4px',      // Medium
    'lg':       '6px',      // Large
    'xl':       '8px',      // X-Large
    'full':     '9999px',   // Circular
  },

  /**
   * Shadow — extracted from Figma (Shadow 2 / Shadow 4)
   * Apply via Tailwind boxShadow when uncommenting in tailwind.tokens.ts
   */
  shadow: {
    // 'sm': '0 2px 4px rgba(0,0,0,0.08)',  // Shadow 2
    // 'md': '0 4px 8px rgba(0,0,0,0.12)',  // Shadow 4
  },

  /**
   * Non-theme colors (semantic, neutral)
   * Theme colors (sp-primary, sp-darker, etc.) → see tailwind.theme-palette.ts
   */
  colors: {},
} as const;
