/**
 * tokens.ts
 *
 * GENERATED BY BRIDGE — DO NOT MODIFY MANUALLY.
 * Run `/design-workflow setup` to regenerate from Figma variables.
 *
 * This file contains all design tokens extracted from Figma variable collections:
 * - Spacing
 * - Typography (font sizes + line heights)
 * - Colors (non-theme colors — semantic, neutral, etc.)
 * - Border radius
 * - Shadows
 *
 * Figma structure: separate collections per token type.
 * Only the default mode (light) is used — dark mode is ignored.
 */

// TODO: This file will be generated by Bridge when /design-workflow setup is run.
// The structure below is a placeholder showing the expected format.

export const figmaTokens = {
  spacing: {
    // Will be populated by Bridge from Figma spacing collection
  },
  fontSize: {
    // Will be populated by Bridge from Figma typography collection
    // Format: { 'name': ['size', { lineHeight: 'value' }] }
  },
  borderRadius: {
    // Will be populated by Bridge from Figma radius variables
  },
  shadow: {
    // Will be populated by Bridge from Figma shadow/effect variables
  },
  colors: {
    // Non-theme colors (semantic, neutral, etc.)
    // Theme colors (sp-*) are handled by generateThemePalette.ts
  },
} as const;
